# Generated by Django 4.2.4 on 2023-08-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(blank=True, default='usuarios/avatar/default_user.png', null=True, upload_to='usuarios/avatar/'),
        ),
    ]
